import type { WorkflowSpec } from "./workflow-tool.js";

export const EQUITY_RESEARCH_WORKFLOWS: WorkflowSpec[] = [
  {
    toolName: "equity_research_catalysts",
    label: "Catalyst Calendar",
    commandName: "/catalysts",
    description: "View or update the catalyst calendar.",
    argHint: "[timeframe, e.g. 'next 2 weeks']",
    primarySkill: "catalyst-calendar",
    skillNames: ["catalyst-calendar"],
    requiredInputs: [],
    deliverables: ["Catalyst calendar", "Near-term catalyst summary"],
    targetOptional: true,
  },
  {
    toolName: "equity_research_earnings_preview",
    label: "Earnings Preview",
    commandName: "/earnings-preview",
    description: "Build a pre-earnings preview with scenarios.",
    argHint: "[company ticker]",
    primarySkill: "earnings-preview",
    skillNames: ["earnings-preview"],
    requiredInputs: ["company ticker"],
    deliverables: ["Pre-earnings preview", "Bull/base/bear scenario summary"],
  },
  {
    toolName: "equity_research_earnings",
    label: "Earnings Update",
    commandName: "/earnings",
    description: "Analyze quarterly earnings and create an earnings update report.",
    argHint: "[company name or ticker] [quarter, e.g. Q3 2024]",
    primarySkill: "earnings-analysis",
    skillNames: ["earnings-analysis"],
    requiredInputs: ["company name or ticker"],
    deliverables: ["Earnings update report", "Beat/miss and thesis-impact summary"],
  },
  {
    toolName: "equity_research_initiate",
    label: "Initiating Coverage",
    commandName: "/initiate",
    description: "Create an initiating coverage report.",
    argHint: "[company ticker]",
    primarySkill: "initiating-coverage",
    skillNames: ["initiating-coverage"],
    requiredInputs: ["company ticker"],
    deliverables: ["Initiating coverage workflow plan", "Institutional-quality initiation outline"],
    notes: [
      "The migrated skill preserves the source plugin's original five-task initiation workflow.",
    ],
  },
  {
    toolName: "equity_research_model_update",
    label: "Model Update",
    commandName: "/model-update",
    description: "Update a financial model with new data.",
    argHint: "[company ticker]",
    primarySkill: "model-update",
    skillNames: ["model-update"],
    requiredInputs: ["company ticker"],
    deliverables: ["Updated model workflow plan", "Key assumption and estimate changes"],
  },
  {
    toolName: "equity_research_morning_note",
    label: "Morning Note",
    commandName: "/morning-note",
    description: "Draft a morning meeting note.",
    primarySkill: "morning-note",
    skillNames: ["morning-note"],
    requiredInputs: [],
    deliverables: ["Morning meeting note", "Overnight developments summary"],
    targetOptional: true,
  },
  {
    toolName: "equity_research_screen",
    label: "Idea Screen",
    commandName: "/screen",
    description: "Run a stock screen or generate investment ideas.",
    argHint: "[screen criteria, e.g. 'undervalued midcap tech']",
    primarySkill: "idea-generation",
    skillNames: ["idea-generation"],
    requiredInputs: ["screen criteria"],
    deliverables: ["Idea screen output", "Thematic or quantitative idea shortlist"],
  },
  {
    toolName: "equity_research_sector",
    label: "Sector Overview",
    commandName: "/sector",
    description: "Create a sector overview report.",
    argHint: "[sector or industry]",
    primarySkill: "sector-overview",
    skillNames: ["sector-overview"],
    requiredInputs: ["sector or industry"],
    deliverables: ["Sector overview report", "Competitive and investment implications summary"],
  },
  {
    toolName: "equity_research_thesis",
    label: "Thesis Tracker",
    commandName: "/thesis",
    description: "Create or update an investment thesis.",
    argHint: "[company ticker]",
    primarySkill: "thesis-tracker",
    skillNames: ["thesis-tracker"],
    requiredInputs: ["company ticker"],
    deliverables: ["Investment thesis update", "Catalysts and risk monitor summary"],
  },
];
