import type { WorkflowSpec } from "./workflow-tool.js";

export const WEALTH_MANAGEMENT_WORKFLOWS: WorkflowSpec[] = [
  {
    toolName: "wealth_management_client_report",
    label: "Client Report",
    commandName: "/client-report",
    description: "Generate a client performance report.",
    argHint: "[client name] [period, e.g. Q4 2025]",
    primarySkill: "client-report",
    skillNames: ["client-report"],
    requiredInputs: ["client name"],
    deliverables: ["Client performance report", "Period-over-period summary"],
  },
  {
    toolName: "wealth_management_client_review",
    label: "Client Review Prep",
    commandName: "/client-review",
    description: "Prep for a client review meeting.",
    argHint: "[client name]",
    primarySkill: "client-review",
    skillNames: ["client-review"],
    requiredInputs: ["client name"],
    deliverables: ["Client review meeting package", "Allocation and talking-points summary"],
  },
  {
    toolName: "wealth_management_financial_plan",
    label: "Financial Plan",
    commandName: "/financial-plan",
    description: "Build or update a financial plan.",
    argHint: "[client name]",
    primarySkill: "financial-plan",
    skillNames: ["financial-plan"],
    requiredInputs: ["client name"],
    deliverables: [
      "Financial plan update",
      "Retirement, estate, education, and cash-flow action items",
    ],
  },
  {
    toolName: "wealth_management_proposal",
    label: "Investment Proposal",
    commandName: "/proposal",
    description: "Create an investment proposal for a prospect.",
    argHint: "[prospect name]",
    primarySkill: "investment-proposal",
    skillNames: ["investment-proposal"],
    requiredInputs: ["prospect name"],
    deliverables: ["Investment proposal", "Prospect-specific allocation rationale"],
  },
  {
    toolName: "wealth_management_rebalance",
    label: "Portfolio Rebalance",
    commandName: "/rebalance",
    description: "Analyze drift and generate rebalancing trades.",
    argHint: "[client name or account]",
    primarySkill: "portfolio-rebalance",
    skillNames: ["portfolio-rebalance"],
    requiredInputs: ["client name or account"],
    deliverables: ["Rebalancing recommendations", "Tax-aware trade summary"],
  },
  {
    toolName: "wealth_management_tlh",
    label: "Tax-Loss Harvesting",
    commandName: "/tlh",
    description: "Identify tax-loss harvesting opportunities.",
    argHint: "[client name or account]",
    primarySkill: "tax-loss-harvesting",
    skillNames: ["tax-loss-harvesting"],
    requiredInputs: ["client name or account"],
    deliverables: ["Tax-loss harvesting scan", "Replacement-security and wash-sale guidance"],
  },
];
