import type { WorkflowSpec } from "./workflow-tool.js";

export const PRIVATE_EQUITY_WORKFLOWS: WorkflowSpec[] = [
  {
    toolName: "private_equity_ai_readiness",
    label: "AI Readiness Scan",
    commandName: "/ai-readiness",
    description: "Scan the portfolio for the highest-leverage AI opportunities.",
    argHint: "[path to quarterly materials folder, or company names]",
    primarySkill: "ai-readiness",
    skillNames: ["ai-readiness"],
    requiredInputs: ["portfolio companies or quarterly materials"],
    deliverables: ["Portfolio AI opportunity scan", "Prioritized EBITDA-impact shortlist"],
  },
  {
    toolName: "private_equity_dd_checklist",
    label: "Due Diligence Checklist",
    commandName: "/dd-checklist",
    description: "Generate a due diligence checklist.",
    argHint: "[company name]",
    primarySkill: "dd-checklist",
    skillNames: ["dd-checklist"],
    requiredInputs: ["company name"],
    deliverables: ["Due diligence checklist", "Status and workstream tracker"],
  },
  {
    toolName: "private_equity_dd_prep",
    label: "Diligence Meeting Prep",
    commandName: "/dd-prep",
    description: "Prep for a diligence meeting or expert call.",
    argHint: "[company name] [meeting type]",
    primarySkill: "dd-meeting-prep",
    skillNames: ["dd-meeting-prep"],
    requiredInputs: ["company name and meeting type"],
    deliverables: ["Diligence prep pack", "Targeted questions and red flags"],
  },
  {
    toolName: "private_equity_ic_memo",
    label: "IC Memo",
    commandName: "/ic-memo",
    description: "Draft an investment committee memo.",
    argHint: "[company name]",
    primarySkill: "ic-memo",
    skillNames: ["ic-memo"],
    requiredInputs: ["company name"],
    deliverables: ["Investment committee memo", "Decision-ready deal summary"],
  },
  {
    toolName: "private_equity_portfolio",
    label: "Portfolio Monitoring",
    commandName: "/portfolio",
    description: "Review portfolio company performance.",
    argHint: "[company name or path to financial package]",
    primarySkill: "portfolio-monitoring",
    skillNames: ["portfolio-monitoring"],
    requiredInputs: ["company name or financial package"],
    deliverables: ["Portfolio performance review", "Variance and KPI summary"],
  },
  {
    toolName: "private_equity_returns",
    label: "Returns Analysis",
    commandName: "/returns",
    description: "Build IRR/MOIC sensitivity tables.",
    argHint: "[company or deal parameters]",
    primarySkill: "returns-analysis",
    skillNames: ["returns-analysis"],
    requiredInputs: ["company or deal parameters"],
    deliverables: ["IRR / MOIC sensitivity tables", "Key returns driver summary"],
  },
  {
    toolName: "private_equity_screen_deal",
    label: "Deal Screen",
    commandName: "/screen-deal",
    description: "Screen an inbound deal (CIM or teaser).",
    argHint: "[path to CIM/teaser file]",
    primarySkill: "deal-screening",
    skillNames: ["deal-screening"],
    requiredInputs: ["path to CIM/teaser file"],
    deliverables: ["Inbound deal screen", "Fit assessment against fund criteria"],
  },
  {
    toolName: "private_equity_source",
    label: "Deal Sourcing",
    commandName: "/source",
    description: "Source deals and draft founder outreach.",
    argHint: "[sector or criteria, e.g. 'industrial services in Texas $10-50M']",
    primarySkill: "deal-sourcing",
    skillNames: ["deal-sourcing"],
    requiredInputs: ["sector or sourcing criteria"],
    deliverables: ["Target company sourcing list", "Draft founder outreach angles"],
    notes: [
      "The migrated workflow preserves the CRM-aware sourcing prompt but does not add CRM integration.",
    ],
  },
  {
    toolName: "private_equity_unit_economics",
    label: "Unit Economics",
    commandName: "/unit-economics",
    description: "Analyze unit economics (ARR cohorts, LTV/CAC, retention).",
    argHint: "[company name or path to data]",
    primarySkill: "unit-economics",
    skillNames: ["unit-economics"],
    requiredInputs: ["company name or path to data"],
    deliverables: ["Unit economics analysis", "Retention and cohort quality summary"],
  },
  {
    toolName: "private_equity_value_creation",
    label: "Value Creation Plan",
    commandName: "/value-creation",
    description: "Build a post-acquisition value creation plan.",
    argHint: "[company name]",
    primarySkill: "value-creation-plan",
    skillNames: ["value-creation-plan"],
    requiredInputs: ["company name"],
    deliverables: ["Value creation roadmap", "100-day plan and KPI dashboard"],
  },
];
