export const OBS_ERROR_CODES = {
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  ROUTE_NOT_BOUND: "ROUTE_NOT_BOUND",
  PAIRING_TOKEN_INVALID: "PAIRING_TOKEN_INVALID",
  INBOUND_FORWARD_FAILED: "INBOUND_FORWARD_FAILED",
  OUTBOUND_PROVIDER_FAILED: "OUTBOUND_PROVIDER_FAILED",
  QUEUE_RETRY_EXHAUSTED: "QUEUE_RETRY_EXHAUSTED",
  CHANNEL_POLL_CONFLICT: "CHANNEL_POLL_CONFLICT",
} as const;

export type ObservabilityErrorCode = (typeof OBS_ERROR_CODES)[keyof typeof OBS_ERROR_CODES];
