import type { WorkflowSpec } from "./workflow-tool.js";

export const FINANCIAL_ANALYSIS_WORKFLOWS: WorkflowSpec[] = [
  {
    toolName: "financial_analysis_three_statement_model",
    label: "3-Statement Model",
    commandName: "/3-statement-model",
    description: "Fill out a 3-statement financial model template.",
    argHint: "[path to template file]",
    primarySkill: "3-statement-model",
    skillNames: ["3-statement-model"],
    requiredInputs: ["path to template file"],
    deliverables: [
      "Completed 3-statement model template",
      "Population notes and validation checkpoints",
    ],
    notes: ["The migrated workflow still expects the user to provide or identify a template file."],
  },
  {
    toolName: "financial_analysis_check_deck",
    label: "Deck Quality Check",
    commandName: "/check-deck",
    description: "QC a presentation deck for errors and consistency.",
    argHint: "[path to .pptx file]",
    primarySkill: "ib-check-deck",
    skillNames: ["ib-check-deck"],
    requiredInputs: ["path to .pptx file"],
    deliverables: [
      "Presentation QC findings",
      "Slide-level formatting, consistency, and data issue list",
    ],
    notes: ["The source command referred to check-deck; the migrated skill name is ib-check-deck."],
  },
  {
    toolName: "financial_analysis_competitive_analysis",
    label: "Competitive Analysis",
    commandName: "/competitive-analysis",
    description: "Create a competitive landscape analysis.",
    argHint: "[company or industry]",
    primarySkill: "competitive-analysis",
    skillNames: ["competitive-analysis"],
    requiredInputs: ["company or industry"],
    deliverables: ["Competitive landscape analysis", "Peer positioning summary"],
  },
  {
    toolName: "financial_analysis_comps",
    label: "Comparable Company Analysis",
    commandName: "/comps",
    description: "Build a comparable company analysis with trading multiples.",
    argHint: "[company name or ticker]",
    primarySkill: "comps-analysis",
    skillNames: ["comps-analysis"],
    requiredInputs: ["company name or ticker"],
    deliverables: ["Comparable company analysis workbook", "Median / quartile valuation summary"],
    notes: ["Prefer configured institutional data connectors over open web search."],
  },
  {
    toolName: "financial_analysis_dcf",
    label: "DCF Valuation",
    commandName: "/dcf",
    description: "Build a DCF valuation model with comps-informed terminal multiples.",
    argHint: "[company name or ticker]",
    primarySkill: "dcf-model",
    skillNames: ["comps-analysis", "dcf-model"],
    requiredInputs: ["company name or ticker"],
    deliverables: [
      "Comparable company analysis workbook",
      "DCF valuation model with scenarios and sensitivities",
      "Valuation summary",
    ],
    notes: ["Prefer configured institutional data connectors over open web search."],
  },
  {
    toolName: "financial_analysis_debug_model",
    label: "Model Audit",
    commandName: "/debug-model",
    description: "Debug and audit a financial model for errors.",
    argHint: "[path to .xlsx model file]",
    primarySkill: "audit-xls",
    skillNames: ["audit-xls"],
    requiredInputs: ["path to .xlsx model file"],
    deliverables: ["Model integrity audit findings", "Recommended formula and logic fixes"],
    notes: ["Use the migrated audit-xls skill with model-focused scope."],
  },
  {
    toolName: "financial_analysis_lbo",
    label: "LBO Model",
    commandName: "/lbo",
    description: "Build an LBO model for a PE acquisition.",
    argHint: "[company name or deal details]",
    primarySkill: "lbo-model",
    skillNames: ["lbo-model"],
    requiredInputs: ["company name or deal details"],
    deliverables: ["LBO model with sources and uses", "Returns sensitivity summary"],
  },
  {
    toolName: "financial_analysis_ppt_template",
    label: "PPT Template Skill Builder",
    commandName: "/ppt-template",
    description: "Create a reusable PPT template skill from a PowerPoint template file.",
    argHint: "[path to .pptx or .potx file]",
    primarySkill: "ppt-template-creator",
    skillNames: ["ppt-template-creator", "skill-creator"],
    requiredInputs: ["path to .pptx or .potx file"],
    deliverables: ["Reusable PowerPoint template skill package", "Validation example presentation"],
    notes: [
      "OpenClaw preserves the skill-authoring workflow but does not add native PowerPoint automation.",
    ],
  },
];
