import type { WorkflowSpec } from "./workflow-tool.js";

export const INVESTMENT_BANKING_WORKFLOWS: WorkflowSpec[] = [
  {
    toolName: "investment_banking_buyer_list",
    label: "Buyer Universe",
    commandName: "/buyer-list",
    description: "Build a buyer universe for a sell-side process.",
    argHint: "[company or sector]",
    primarySkill: "buyer-list",
    skillNames: ["buyer-list"],
    requiredInputs: ["company or sector"],
    deliverables: ["Buyer universe workbook", "Tiered strategic and financial acquirer summary"],
  },
  {
    toolName: "investment_banking_cim",
    label: "CIM Builder",
    commandName: "/cim",
    description: "Draft a Confidential Information Memorandum.",
    argHint: "[company name]",
    primarySkill: "cim-builder",
    skillNames: ["cim-builder"],
    requiredInputs: ["company name"],
    deliverables: [
      "Draft CIM structure and narrative outline",
      "Source-material request checklist",
    ],
  },
  {
    toolName: "investment_banking_deal_tracker",
    label: "Deal Tracker",
    commandName: "/deal-tracker",
    description: "Track and review live deal pipeline.",
    primarySkill: "deal-tracker",
    skillNames: ["deal-tracker"],
    requiredInputs: [],
    deliverables: ["Live deal pipeline review", "Milestones and action-item summary"],
    targetOptional: true,
  },
  {
    toolName: "investment_banking_merger_model",
    label: "Merger Model",
    commandName: "/merger-model",
    description: "Build an accretion/dilution merger model.",
    argHint: "[acquirer] acquiring [target]",
    primarySkill: "merger-model",
    skillNames: ["merger-model"],
    requiredInputs: ["acquirer and target"],
    deliverables: ["Accretion / dilution merger model", "Key deal sensitivity summary"],
  },
  {
    toolName: "investment_banking_one_pager",
    label: "One-Pager Strip Profile",
    commandName: "/one-pager",
    description: "Create a one-page company strip profile using a branded PPT template.",
    argHint: "[company name or ticker]",
    primarySkill: "strip-profile",
    skillNames: ["strip-profile", "pitch-deck"],
    requiredInputs: ["company name or ticker"],
    deliverables: ["One-page strip profile slide", "Supporting company snapshot and key metrics"],
    notes: ["If a branded template skill exists, apply it before final delivery."],
  },
  {
    toolName: "investment_banking_process_letter",
    label: "Process Letter",
    commandName: "/process-letter",
    description: "Draft a process letter or bid instructions.",
    argHint: "[IOI or final bid]",
    primarySkill: "process-letter",
    skillNames: ["process-letter"],
    requiredInputs: ["process stage or letter type"],
    deliverables: [
      "Draft process letter or bid instructions",
      "Process timeline and next-step summary",
    ],
  },
  {
    toolName: "investment_banking_teaser",
    label: "Blind Teaser",
    commandName: "/teaser",
    description: "Draft an anonymous one-page teaser.",
    argHint: "[company name]",
    primarySkill: "teaser",
    skillNames: ["teaser"],
    requiredInputs: ["company name"],
    deliverables: ["Anonymous one-page teaser", "Sanitized company positioning summary"],
  },
];
